apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-configmap
data:
  APPLICATION_VERSION: {{ $.Values.tagversion }}
  {{- range $key, $value := $.Values.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
