apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    tier: backend
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
  {{- if .Values.metricsPort }}
  - name: metrics
    protocol: TCP
    port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
  {{ end }}
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
